# https://taskfile.dev

version: '3'

set:
  - pipefail
shopt:
  - globstar

includes:
  k8s-bootstrap: .taskfiles/k8s-bootstrap/Taskfile.yaml
  talos: .taskfiles/talos/Taskfile.yaml

vars:
  K8S_DIR: "{{.ROOT_DIR}}/kubernetes"
  KUBECONFIG: "{{.K8S_DIR}}/kubeconfig"
  MINIJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/.minijinja.toml"
  TALOSCONFIG: "{{.K8S_DIR}}/talos/clusterconfig/talosconfig"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"
  MINIJINJA_CONFIG_FILE: "{{.MINIJINJA_CONFIG_FILE}}"
  TALOSCONFIG: "{{.TALOSCONFIG}}"

tasks:
  default:
    silent: true
    cmd: task --list

