apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
  namespace: default
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: tls-backend
    sectionName: https
  validation:
    hostname: unifi-controller.selfhosted.svc.cluster.local
    caCertificateRefs:
    - name: unifi-ca
      group: ''
      kind: ConfigMap
    subjectAltNames:
      - type: Hostname
        hostname: unifi-controller.selfhosted.svc.cluster.local