apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: enable-backend-tls
  namespace: default
spec:
  targetRefs:
  - group: ''
    kind: Service
    name: tls-backend
    sectionName: https
  validation:
    caCertificateRefs:
    - name: unifi-ca-secret
      group: ''
      kind: Secret
    SubjectAltNames: unifi-controller.selfhosted.svc.cluster.local