apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-controller
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: unifi-secret
    creationPolicy: Owner
    template:
      data:
        cert.pem: "{{ .UNIFI_CERT_CERTIFICATE }}"
        chain.pem: "{{ .UNIFI_CERT_CHAIN }}"
        privkey.pem: "{{ .UNIFI_CERT_KEY }}"        
  dataFrom:
    - find:
        path: UNIFI_
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"