---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      unifi:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/jacobalberty/unifi-docker
              tag: v9.0.114@sha256:d5c9f87e643854bec4d0c15f6cbeec75510a449a7ec46f1e223eded858add480
            env:
              TZ: "Europe/Berlin"
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
          logs:
            image:
              repository: docker.io/library/busybox
              tag: latest
            args:
              - /bin/bash
              - -c
              - tail -F /unifi/log/*.log
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    service:
      app:
        controller: unifi
        ports:
          ui:
            port: &uiport 8443
          inform:
            port: &informport 8080
          #stun:
          #  port: &stunport 3478
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        advancedMounts:
          unifi:
            app:
              - path: /unifi
      logs:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        advancedMounts:
          unifi:
            app:
              - path: /unifi/log
    route:
      ui:
        hostnames:
          - unifi.apps.mrtb.io
        parentRefs:
          - name: gateway
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: unifi
                port: *uiport
      inform:
        hostnames:
          - unifi-inform.apps.mrtb.io
        parentRefs:
          - name: gateway
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: unifi
                port: *informport
            matches:
              - path:
                  type: Prefix
                  value: /inform
      #stun:
      #  kind: UDPRoute
      #  parentRefs:
      #    - name: gateway
      #      namespace: kube-system
      #      sectionName: stun
      #  rules:
      #    - backendRefs:
      #        - name: unifi
      #          port: *stunport
