apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: njalla-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: njalla-api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: CERT_MANAGER_NJALLA_API_KEY
