---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-proxy-config
data:
  unifi.conf: |
    upstream unifi-service-ui {
      server unifi-controller.selfhosted.svc.cluster.local:8443;
    }
    upstream unifi-service-inform {
      server unifi-controller.selfhosted.svc.cluster.local:8080;
    }  
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      location / {
        #proxy_set_header X-Real-IP \$remote_addr;
        #proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_pass https://unifi-service-ui;
        proxy_ssl_verify off;
        proxy_redirect off;
      }
      location /inform {
        #proxy_set_header X-Real-IP \$remote_addr;
        #proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_pass https://unifi-service-inform;
        proxy_ssl_verify off;
        proxy_redirect off;
      }
    }